### ISSUE TITLE
Error reading

### ISSUE THREAD

**Issue by sysmat** [dhatim/fastexcel#109]
* java:8
* fastexcel-reader:0.10.15
* error:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found class org.apache.poi.util.POILogger, but interface was expected
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.parseRelationshipsPart(PackageRelationshipCollection.java:303)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:163)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:133)
	at org.apache.poi.openxml4j.opc.PackagePart.loadRelationships(PackagePart.java:570)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:734)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:204)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.open(ReadableWorkbook.java:200)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:68)

```

**Comment by ochedru** [comment]
This could be a conflict due to different versions of Apache POI referenced by your project. Fastexcel 0.0.15 uses Apache POI 4.1.1.

**Comment by rzymek** [comment]
Closing. fastexcel no longer has dependency on Apache POI
