### ISSUE TITLE
NumberFormatExpection on initial read of sheet

### ISSUE THREAD

**Issue by LTielenRD** [dhatim/fastexcel#122]
Hiya while trying to read a xlsx file, I'm immediately getting the following exception:

> For input string: "": java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.dhatim.fastexcel.reader.RowSpliterator.parseString(RowSpliterator.java:156)
	at org.dhatim.fastexcel.reader.RowSpliterator.parseCell(RowSpliterator.java:112)
	at org.dhatim.fastexcel.reader.RowSpliterator.next(RowSpliterator.java:94)
	at org.dhatim.fastexcel.reader.RowSpliterator.tryAdvance(RowSpliterator.java:47)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.dhatim.fastexcel.reader.Sheet.read(Sheet.java:55)

**Comment by rzymek** [comment]
Could you share the xlsx that causes this exception?

**Comment by LTielenRD** [comment]
Do you still need me to share the excel file?

**Comment by rzymek** [comment]
Release 0.10.21 includes a possible fix for this issue. 
Could verify that it solves this problem? 
If not then - yes - I'll like to take a look at that excel file.

**Comment by LTielenRD** [comment]
seems to have been fixed indeed, thanks!
