### ISSUE TITLE
Reading empty file leads to error and resource leak

### ISSUE THREAD

**Issue by coconut2015** [dhatim/fastexcel#168]
Create an empty Excel file using Excel program to open a Blank workbook and then save it.  The attached is an example.
[empty.xlsx](https://github.com/dhatim/fastexcel/files/6826787/empty.xlsx)

Either ``new ReadableWorkbook (file)`` or ``new ReadableWorkbook (new FileInputStream (file))`` would get an exception.  The backtrace is:

```
java.lang.NullPointerException
        at org.dhatim.fastexcel.reader.OPCPackage.getEntryContent(OPCPackage.java:97)
        at org.dhatim.fastexcel.reader.OPCPackage.getSharedStrings(OPCPackage.java:93)
        at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:52)
        at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:37)
```

And the annoying part is that ZipFile would generate an unwanted message:
```
Cleaning up unclosed ZipFile for archive /tmp/test.18796/empty.xlsx
```

**Comment by coconut2015** [comment]
Oops, #151 already covered it.
