### ISSUE TITLE
Constructor are default scope in v 0.9.3

### ISSUE THREAD

**Issue by anandagowdan3** [dhatim/fastexcel#24]
I was trying to use the Range, StyleSetter etc., Couldn't work because the constructors were default scope.

**Comment by ochedru** [comment]
This is by design.
Do not construct these objects yourself, use instead public methods `style()` and `range()` on class [`Worksheet`](https://github.com/dhatim/fastexcel/blob/master/fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java).

**Comment by anandagowdan3** [comment]
Thank you.
One more doubt.
I'm working on a legacy project. Built using Java 1.6.
Not maven project.
I want to use fasterexcel plug in. I upgraded Java to 1.8. But it's throwing major.minor incompatible error at runtime. No compile time error.
Please help.

**Comment by anandagowdan3** [comment]
Thank you for your response

The details are as follows : 

[root@smsc ~]# java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

log shows as follows

Servlet.service() for servlet SignalingLinkLoadStatusServlet threw exception
java.lang.UnsupportedClassVersionError: org/dhatim/fastexcel/Workbook : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:1815)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:869)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1322)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1201)
        at com.teledna.javabean.operator.misreports.mocapping.ExportToExcel.exportSignalingLinkLoadStatusReports(ExportToExcel.java:1346)
        at com.teledna.servlet.operator.SignalingLinkLoad.SignalingLinkLoadStatusServlet.doPost(SignalingLinkLoadStatusServlet.java:217)
        at com.teledna.servlet.operator.SignalingLinkLoad.SignalingLinkLoadStatusServlet.doGet(SignalingLinkLoadStatusServlet.java:55)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:524)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
        at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
        at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
        at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
        at java.lang.Thread.run(Thread.java:619)

**Comment by ochedru** [comment]
Version 52.0 is indeed java 8 as expected (the fastexcel jar is built with java 8), but I guess your tomcat is using another java version: please check `JAVA_HOME` in your tomcat installation.

**Comment by anandagowdan3** [comment]
Thank you very much ochedru. I'm recompiling whole deployment.
