### ISSUE TITLE
Flushing in a multi-sheet workbook

### ISSUE THREAD

**Issue by ps-b2p** [dhatim/fastexcel#357]
Hi all.
I have an application that generates an excel document with many sheets. A lot of data is unloaded into this document, as a result of which I have to call the flush method on each sheet so as not to keep this data in memory (as described in this [comment](https://github.com/dhatim/fastexcel/issues/41#issuecomment-462842761)). Here is a code example:
```
try (
        FileOutputStream baos = new FileOutputStream("src/main/resources/test.xlsx");
        Workbook workbook = new Workbook(baos, "Application", null);
) {

    Worksheet sheet0 = workbook.newWorksheet("Sheet0");
    sheet0.value(0, 0, "hello");
    sheet0.flush();

    Worksheet sheet1 = workbook.newWorksheet("Sheet1");
    sheet1.value(0, 0, "World");
    sheet1.flush();

    Worksheet sheet2 = workbook.newWorksheet("Sheet2");
    sheet2.value(0, 0, "!!!!!");
    sheet2.flush();

} catch (Exception e) {
    e.printStackTrace();
}
```
But I get an error when closing such a workbook.
```
java.lang.IllegalStateException: not current zip current
	at com.github.rzymek.opczip.OpcOutputStream.closeEntry(OpcOutputStream.java:59)
	at org.dhatim.fastexcel.Workbook.endFile(Workbook.java:345)
	at org.dhatim.fastexcel.Worksheet.finish(Worksheet.java:936)
	at org.dhatim.fastexcel.Worksheet.close(Worksheet.java:816)
	at org.dhatim.fastexcel.Workbook.finish(Workbook.java:132)
	at org.dhatim.fastexcel.Workbook.close(Workbook.java:117)
```
What am I doing wrong? Is there any workaround?
Thank you in advance!

**Comment by meiMingle** [comment]
Maybe you should replace `flush()` with `finish()`

**Comment by ps-b2p** [comment]
Yes, it did the trick. Thanks a lot!
