### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory

### ISSUE THREAD

**Issue by Tanzin01** [dhatim/fastexcel#428]
Im trying read a file but getting this crash error

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.example.sheetmyapplication11, PID: 11383
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/fasterxml/aalto/AsyncXMLInputFactory;
	at org.dhatim.fastexcel.reader.OPCPackage.extractPartEntriesFromContentTypes(OPCPackage.java:83)
	at org.dhatim.fastexcel.reader.OPCPackage.<init>(OPCPackage.java:48)
	at org.dhatim.fastexcel.reader.OPCPackage.<init>(OPCPackage.java:38)
	at org.dhatim.fastexcel.reader.OPCPackage.open(OPCPackage.java:141)
	at org.dhatim.fastexcel.reader.OPCPackage.open(OPCPackage.java:137)
	at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:40)
	at com.example.sheetmyapplication11.ExcelHandler.ExcelHandler.readExcel(ExcelHandler.java:43)
	at com.example.sheetmyapplication11.fragments.TableScreenViewModel$loadData$1.invokeSuspend(TableScreenViewModel.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f6db1f7, Dispatchers.IO]
Caused by: java.lang.ClassNotFoundException: com.fasterxml.aalto.AsyncXMLInputFactory
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codehaus/stax2/XMLInputFactory2;
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.stax2.XMLInputFactory2
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
	... 16 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLInputFactory" on path: DexPathList[[zip file "/data/app/~~FmGEK8RF5SDZff8jTQ5dCg==/com.example.sheetmyapplication11-VA1OQvJbxwwSta3gbUQFPw==/base.apk"],nativeLibraryDirectories=[/data/app/~~FmGEK8RF5SDZff8jTQ5dCg==/com.example.sheetmyapplication11-VA1OQvJbxwwSta3gbUQFPw==/lib/arm64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 16 more
```

Let me know if more info is needed

**Comment by MrBrowner** [comment]
I'm trying use this lib in my sample Android project.
I'm getting the same error as this, when trying to read file

How it's got resolved?
Any help is much appreciated.

Thanks & Regards.

**Comment by MrBrowner** [comment]
I'm trying use this lib in my sample Android project.
I'm getting the same error as this, when trying to read file

How it's got resolved?
Any help is much appreciated.

Thanks & Regards.
