### ISSUE TITLE
Error while Reading excel file

### ISSUE THREAD

**Issue by AslanDevbrat** [dhatim/fastexcel#87]
I am Trying to read excel file but I am stuck at the  

> ReadableWorkbook wb = new ReadableWorkbook(Objects.requireNonNull(inputStream)

Following is Simple app to read data from excel file.

              public void getit(View view) throws IOException {
        File inputFile = new File("/storage/emulated/0/police/test.xlsx");
        inputFile.setReadable(true);
        if(inputFile.canRead())
            Toast.makeText(this,"it can read",Toast.LENGTH_SHORT).show();
        InputStream inputStream = null;
        try {
            inputStream = new FileInputStream(inputFile);
            Log.d(String.valueOf(this), "happen");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
       
        try ( ReadableWorkbook wb = new ReadableWorkbook(Objects.requireNonNull(inputStream))) {

            Sheet sheet = wb.getFirstSheet();
            try(Stream<Row> rows = sheet.openStream()){
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    rows.forEach(r->{
                        BigDecimal num = r.getCellAsNumber(0).orElse(null);
                        String str = r.getCellAsString(1).orElse(null);
                        Log.i(String.valueOf(this),"cell 1 = "+num+"cell 2 = "+str+"\n");
                    } );
                }

            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }`

And my build.gradle file is 
              apply plugin: 'com.android.application'

                      android {
    compileSdkVersion 29
    buildToolsVersion "29.0.0"
    defaultConfig {
        applicationId "android.example.com.myapplication"
        minSdkVersion 20
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }

}

                dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'org.dhatim:fastexcel-reader:0.10.2'

}

I  am getting the following error

        Process: android.example.com.myapplication, PID: 30869
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22298)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:5619) 
        at android.view.View$PerformClick.run(View.java:22298) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
     Caused by: java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
        at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:218)
        at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:201)
        at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:162)
        at org.apache.poi.openxml4j.util.ZipSecureFile.<init>(ZipSecureFile.java:122)
        at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:205)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:140)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:271)
        at org.dhatim.fastexcel.reader.ReadableWorkbook.open(ReadableWorkbook.java:192)
        at org.dhatim.fastexcel.reader.ReadableWorkbook.<init>(ReadableWorkbook.java:52)
        at android.example.com.myapplication.MainActivity.getit(MainActivity.java:46)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:5619) 
        at android.view.View$PerformClick.run(View.java:22298) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by rzymek** [comment]
`File.toPath()` requires Android API level 26. I think you need to increment `minSdkVersion`

**Comment by AslanDevbrat** [comment]
@rzymek Please check the question again and reply soon

**Comment by rzymek** [comment]
Did you try changing `minSdkVersion` to 26?
