### ISSUE TITLE
IndexOutOfBoundsException during reading xlsx in a streaming way

### ISSUE THREAD

**Issue by 2andrew** [dhatim/fastexcel#88]
Try to read xlsx file and get IndexOutOfBoundsException after full file reading.
For example, if I run this code:
```
Sheet sheet = wb.getFirstSheet();
            try (Stream<Row> rows = sheet.openStream()) {
                rows.forEach(r -> {
                    System.out.println(r.getRowNum());
                });
            }
```
For attached file, I get strange output: 
```
1
2
1039685
java.lang.IndexOutOfBoundsException: row-index: 1039685, index: 0, count: 0
	at org.dhatim.fastexcel.reader.Row.getCell(Row.java:41)
	at com.checker.springbootadminclient.temp.translations.Sql3.lambda$main$0(Sql3.java:36)
	at org.dhatim.fastexcel.reader.RowSpliterator.tryAdvance(RowSpliterator.java:52)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.checker.springbootadminclient.temp.translations.Sql3.main(Sql3.java:34)
```
In the same time, rows.count() return correct result.

[Translations.xlsx](https://github.com/dhatim/fastexcel/files/3435846/Translations.xlsx)

**Comment by rzymek** [comment]
Not quite able to reproduce with this test:
```
@Test
void issue88() throws IOException {
  try (InputStream in = getClass().getResourceAsStream("/Translations.xlsx");
     ReadableWorkbook wb = new ReadableWorkbook(in)) {
    Sheet sheet = wb.getFirstSheet();
    try (Stream<Row> rows = sheet.openStream()) {
      rows.forEach(r -> {
        System.out.println(r.getRowNum());
      });
    }
  }
}
```
The output is:
```
1
2
1039685
1039686
1039687
... 
1048574
1048575
1048576
````

Those rows after row 2 are actually present in the xlsx's XML:
```
<row r="1040828" customFormat="false" ht="12.8" hidden="false"
     customHeight="false" outlineLevel="0" collapsed="false"></row>
```
They contain no cells (strange).

I suspect your output it not really from the code you posted. There's no call to `getCell` in your code, but there is one in the call stack. Nevertheless if you'd were to run this:
```
rows.forEach(r -> {
    System.out.println(r.getRowNum());
    r.getCell(0);
});
```
You'd get your exact stack trace. This is expected. There's a reference to cell at colum index that does not exists in row 1039685. Consider using `Row.getCellCount()` or `Row.stream()`.
